"""Initial schema

Revision ID: f0038d702f7e
Revises: 
Create Date: 2026-02-15 15:20:31.339837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0038d702f7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=True),
    sa.Column('last_request_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('association_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents', sa.JSON(), nullable=False),
    sa.Column('consequents', sa.JSON(), nullable=False),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_association_rules_id'), 'association_rules', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['resource', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_logs', ['user', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user'), 'audit_logs', ['user'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('taxonomy_code', sa.String(length=20), nullable=True),
    sa.Column('geographic_region', sa.String(length=50), nullable=True),
    sa.Column('baselines', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_groups_id'), 'peer_groups', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('licensed_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_location', 'providers', ['state', 'city'], unique=False)
    op.create_index('idx_provider_type', 'providers', ['facility_type', 'state'], unique=False)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_npi'), 'providers', ['npi'], unique=True)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('billing_code', sa.String(length=20), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_score', 'anomalies', ['z_score', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_table('capacity_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('violation_date', sa.Date(), nullable=False),
    sa.Column('licensed_capacity', sa.Integer(), nullable=False),
    sa.Column('billed_patients', sa.Integer(), nullable=False),
    sa.Column('excess_percentage', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'violation_date', name='unique_provider_date_violation')
    )
    op.create_index('idx_capacity_provider_date', 'capacity_violations', ['provider_id', 'violation_date'], unique=False)
    op.create_index(op.f('ix_capacity_violations_id'), 'capacity_violations', ['id'], unique=False)
    op.create_index(op.f('ix_capacity_violations_violation_date'), 'capacity_violations', ['violation_date'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('whistleblower_notes', sa.Text(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('settlement_amount', sa.Float(), nullable=True),
    sa.Column('relator_share', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index('idx_case_status', 'cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=True),
    sa.Column('beneficiary_id', sa.String(length=50), nullable=True),
    sa.Column('billing_code', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('place_of_service', sa.String(length=50), nullable=True),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_beneficiary_id'), 'claims', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_claims_billing_code'), 'claims', ['billing_code'], unique=False)
    op.create_index(op.f('ix_claims_claim_date'), 'claims', ['claim_date'], unique=False)
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('evv_gps_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=50), nullable=True),
    sa.Column('claim_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evv_gps_logs_beneficiary_id'), 'evv_gps_logs', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_evv_gps_logs_claim_id'), 'evv_gps_logs', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evv_gps_logs_id'), 'evv_gps_logs', ['id'], unique=False)
    op.create_index(op.f('ix_evv_gps_logs_timestamp'), 'evv_gps_logs', ['timestamp'], unique=False)
    op.create_table('investigation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_investigator_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_source', sa.String(length=50), nullable=True),
    sa.Column('estimated_fraud_amount', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_case_number'), 'investigation_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_investigation_cases_id'), 'investigation_cases', ['id'], unique=False)
    op.create_table('kickback_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_concentration', sa.Float(), nullable=True),
    sa.Column('cash_withdrawal_pattern', sa.Boolean(), nullable=True),
    sa.Column('enrollment_spike_dates', sa.JSON(), nullable=True),
    sa.Column('referral_network', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_kickback_indicators_id'), 'kickback_indicators', ['id'], unique=False)
    op.create_table('pol_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('sudden_spike_score', sa.Integer(), nullable=True),
    sa.Column('max_code_abuse_score', sa.Integer(), nullable=True),
    sa.Column('timing_anomaly_score', sa.Integer(), nullable=True),
    sa.Column('capacity_exceed_score', sa.Integer(), nullable=True),
    sa.Column('referral_concentration_score', sa.Integer(), nullable=True),
    sa.Column('sustained_no_growth_score', sa.Integer(), nullable=True),
    sa.Column('full_results', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('peer_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_pol_results_id'), 'pol_results', ['id'], unique=False)
    op.create_table('provider_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('screening_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('license_verified', sa.Boolean(), nullable=True),
    sa.Column('exclusion_list_check', sa.Boolean(), nullable=True),
    sa.Column('criminal_background_check', sa.Boolean(), nullable=True),
    sa.Column('site_visit_conducted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_screenings_id'), 'provider_screenings', ['id'], unique=False)
    op.create_table('compliance_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audits_id'), 'compliance_audits', ['id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=True),
    sa.Column('evidence_ref', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_case_date', 'timeline_events', ['case_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_date'), 'timeline_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_table('transportation_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lon', sa.Float(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lon', sa.Float(), nullable=True),
    sa.Column('calculated_distance', sa.Float(), nullable=True),
    sa.Column('claimed_distance', sa.Float(), nullable=True),
    sa.Column('is_group_ride', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_index('idx_trip_claim', 'transportation_trips', ['claim_id'], unique=False)
    op.create_index(op.f('ix_transportation_trips_id'), 'transportation_trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transportation_trips_id'), table_name='transportation_trips')
    op.drop_index('idx_trip_claim', table_name='transportation_trips')
    op.drop_table('transportation_trips')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_date'), table_name='timeline_events')
    op.drop_index('idx_timeline_case_date', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_compliance_audits_id'), table_name='compliance_audits')
    op.drop_table('compliance_audits')
    op.drop_index(op.f('ix_provider_screenings_id'), table_name='provider_screenings')
    op.drop_table('provider_screenings')
    op.drop_index(op.f('ix_pol_results_id'), table_name='pol_results')
    op.drop_table('pol_results')
    op.drop_index(op.f('ix_kickback_indicators_id'), table_name='kickback_indicators')
    op.drop_table('kickback_indicators')
    op.drop_index(op.f('ix_investigation_cases_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_case_number'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_evv_gps_logs_timestamp'), table_name='evv_gps_logs')
    op.drop_index(op.f('ix_evv_gps_logs_id'), table_name='evv_gps_logs')
    op.drop_index(op.f('ix_evv_gps_logs_claim_id'), table_name='evv_gps_logs')
    op.drop_index(op.f('ix_evv_gps_logs_beneficiary_id'), table_name='evv_gps_logs')
    op.drop_table('evv_gps_logs')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_billing_code'), table_name='claims')
    op.drop_index(op.f('ix_claims_beneficiary_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index('idx_case_status', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_capacity_violations_violation_date'), table_name='capacity_violations')
    op.drop_index(op.f('ix_capacity_violations_id'), table_name='capacity_violations')
    op.drop_index('idx_capacity_provider_date', table_name='capacity_violations')
    op.drop_table('capacity_violations')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index('idx_anomaly_score', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_providers_npi'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index('idx_provider_type', table_name='providers')
    op.drop_index('idx_provider_location', table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_peer_groups_id'), table_name='peer_groups')
    op.drop_table('peer_groups')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_audit_logs_user'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user_time', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_association_rules_id'), table_name='association_rules')
    op.drop_table('association_rules')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
